{"name": "expected exception", "status": "passed", "parameters": [{"name": "first_para", "value": "None"}, {"name": "second_para", "value": "None"}, {"name": "expected", "value": "<class 'TypeError'>"}], "start": 1577542918689, "stop": 1577542918690, "uuid": "0195158f-0f4b-4bf4-82d5-50972b56e713", "historyId": "c449f34ad3cd0592ef7c209e1406c84c", "testCaseId": "2ec7f2475aae25c72397e4d9deaec871", "fullName": "unit.test_div#test_div_error", "labels": [{"name": "tag", "value": "exception"}, {"name": "parentSuite", "value": "unit"}, {"name": "suite", "value": "test_div"}, {"name": "host", "value": "WIN-1GF9INK28GB"}, {"name": "thread", "value": "3304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit.test_div"}]}