{"name": "expected exception", "status": "passed", "parameters": [{"name": "first_para", "value": "'a'"}, {"name": "second_para", "value": "9"}, {"name": "expected", "value": "<class 'TypeError'>"}], "start": 1577542918654, "stop": 1577542918655, "uuid": "bf879b48-ba95-4647-b7ca-4d55f95d2002", "historyId": "e9acf32b984a1af5523e5d23f663d95d", "testCaseId": "2ec7f2475aae25c72397e4d9deaec871", "fullName": "unit.test_div#test_div_error", "labels": [{"name": "tag", "value": "exception"}, {"name": "parentSuite", "value": "unit"}, {"name": "suite", "value": "test_div"}, {"name": "host", "value": "WIN-1GF9INK28GB"}, {"name": "thread", "value": "3304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit.test_div"}]}