{"name": "expected exception", "status": "passed", "parameters": [{"name": "first_para", "value": "10"}, {"name": "second_para", "value": "'a'"}, {"name": "expected", "value": "<class 'TypeError'>"}], "start": 1577542918625, "stop": 1577542918626, "uuid": "95d69dc9-7c43-4f69-81e6-21ea6b9ea39c", "historyId": "ff5bf49f057baf1139525836ba038d2a", "testCaseId": "2ec7f2475aae25c72397e4d9deaec871", "fullName": "unit.test_div#test_div_error", "labels": [{"name": "tag", "value": "exception"}, {"name": "parentSuite", "value": "unit"}, {"name": "suite", "value": "test_div"}, {"name": "host", "value": "WIN-1GF9INK28GB"}, {"name": "thread", "value": "3304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit.test_div"}]}